language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

env:
  global:
    - SECRET_KEY=superSecretKey
  matrix:
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0

install:
- pip install -r requirements.txt
- yes | pip uninstall Django
- pip install Django==$DJANGO_VERSION
- pip install black==18.6b1 || true

script:
- black --check . || true
- python manage.py test
